### ISSUE TITLE
Some types allow for `any` in @pdc-sdk

### ISSUE THREAD

**Issue by hminsky2002** [PhilanthropyDataCommons/service#1004]
While working on pdc front-end issue [705](https://github.com/PhilanthropyDataCommons/front-end/issues/705)
I discovered that, currently, our @pdc-sdk allows for type 'any' in multiple different schemas. 

![Image](https://github.com/PhilanthropyDataCommons/service/assets/18370464/2f3fc560-a5e8-4216-8354-19de00f4f0fc)
![Image](https://github.com/PhilanthropyDataCommons/service/assets/18370464/f1302f62-624a-4ff2-b669-e5a2edcf4bda)
![Image](https://github.com/PhilanthropyDataCommons/service/assets/18370464/34801497-bf87-4992-887d-03227384c696)

Per my understanding of the sdk and a discussion with @slifty in front-end PR [719](https://github.com/PhilanthropyDataCommons/front-end/pull/719), it seems like these are erroneous and should be fixed to be only of a specific type!

**Comment by slifty** [comment]
The root cause here is that these fields use `allOf` in order to mark certain items as `readonly`.

For instance: https://github.com/PhilanthropyDataCommons/service/blob/c1f7e8717beb727d622bfd4273aaae450ed68dce/src/openapi.json#L199-L206

This is partly related to #854, which would prevent the need to use that pattern.

Unfortunately the components of the swagger ecosystem that add that `& any` are not necessarily directly in our control.  That said, I'll look into whether we can use a different pattern in our specification *or* if it's possible to update the code generation script.

**Comment by slifty** [comment]
OK! It looks like switching to this format does the trick (hat tip https://stackoverflow.com/questions/51402156/how-to-declare-a-ref-property-as-readonly-in-openapi-swagger)

```
					"applicationFormField": {
						"readOnly": true,
						"allOf": [
							{
								"$ref": "#/components/schemas/ApplicationFormField"
							}
						]
					},
```
