### ISSUE TITLE
Unsafe argument of type `any` on presigned post fields

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/service#1011]
When using the `PresignedPostRequestPresignedPost` type, accessing the values from a presigned post `fields` object triggers the ol' unsafe `any` type complaint:

```
Unsafe argument of type `any` assigned to a parameter of type `string | Blob`.
```

E.g.:

```ts
const uploadUsingPresignedPost = async (
	file: File,
	presignedPost: PresignedPostRequestPresignedPost,
) => {
	const formData = new FormData();
	Object.entries(presignedPost.fields).forEach(([key, value]) =>
		// ❌ This is where things break:
		formData.append(key, value),
	);
	// Rest of function omitted
}
```

Unsure if this should be part of https://github.com/PhilanthropyDataCommons/service/issues/1004 or is separate.

**Comment by slifty** [comment]
Now that I'm actually digging into this, this is actually due to the signature of `Object.entries`, *not* due to our type definition.

Object.entries cannot safely guarantee that values are always of a given type -- even if the "Type" of a given variable has only string entities, TypeScript is not saying there aren't *more* than those entities on the object.

So I think what you'll need to do is add a type guard e.g.:

```
	const isValidFormDataValue(value: unknown) value is string | Blob | ...  => typeof value  === 'string' || value instanceof Blob || ...
	
	Object.entries(presignedPost.fields).forEach(([key, value]) =>
		if (isValidFormDataValue(value) {
			formData.append(key, value),
		}
	);
```

^ you might

**Comment by slifty** [comment]
For now I'm marking this as closed as not planned based on the above analysis, that said we can absolutely re-open if that is wrong.

**Comment by reefdog** [comment]
This makes sense! Thanks for the thorough explanation _and_ even tackling the front-end issue that this is linked to! 🙏
