### ISSUE TITLE
Investigate potential versioning race condition

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#109]
We have a few tables that involve multiple versions.  During a [recent review](https://github.com/PhilanthropyDataCommons/service/pull/106#discussion_r1009676223) @bickelj pointed out that there is a potential that the use of a SELECT within the insert query might result in a race condition in the event that two inserts are run simultaneously.

We should look into what it would take to prevent that race condition from happening.

**Comment by bickelj** [comment]
I think we can embrace the race and recover/retry if it happens. And we may not need to bother until we see an actual error happen because it is pretty unlikely. It might be good to know what will happen, though, in a test environment. Setting the transaction level to serializable and having a few retries when they collide should be enough.

**Comment by slifty** [comment]
Marking this as closed per @bickelj's comment above!
