### ISSUE TITLE
Add `funders` endpoints

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#116]
We want to create the concept of a funder (name TBD) -- what organization(s) is the owner of a given opportunity.

**Comment by slifty** [comment]
We probably need to support the idea of multiple funders for a given opportunity.

**Comment by bickelj** [comment]
Keeping track of funders is kind of like provenance tracking for an opportunity, right? But do we also want provenance tracking regarding which system, e.g. which data platform provider, the data came from?

**Comment by bickelj** [comment]
What do you think of these tables?

```
  Outcome {
    int id
    int proposalId
    int funderId
    string outcome
    datetime createdAt
  }
  Funder {
    int id
    string name
    datetime createdAt
  }
  Opportunity {
    int id
    string title
    datetime createdAt
  }
  OpportunityFunders {
    int opportunityId
    int funderId
  }
```

 I suppose from an entity perspective `OpportunityFunders` wouldn't be an entity, it's a table allowing many-to-many Opportunities to Funders.

Opportunity might want a mandatory `originalFunderId` in which case `OpportunityFunders` would become `AdditionalOpportunityFunders`. Either way application-level constraint enforcement will be needed.

Another way might be to let the `Proposal` be to a specific funder rather than linking the funder to the `Opportunity`. Or both could be linked. It would be nice to minimize the number of entities connected to `Funder`, though. If we have the `Proposal` linked to `Funder`, then we can have multiple funders with multiple proposals and skip the link to `Outcome`, but the drawback there is to have duplication of the filled-out proposal fields when submitting to multiple funders.

Thoughts?

**Comment by bickelj** [comment]
Another distinction between the user or system posting data and the foundation on whose behalf it gets posted. This distinction will probably matter for authorization, #255.

**Comment by jasonaowen** [comment]
See also this [internal discussion about the data source](https://chat.opentechstrategies.com/#narrow/stream/66-PDC/topic/Data/near/159279).

**Comment by slifty** [comment]
We might consider thinking about this in #396, but also I don't believe we have use cases related to Funders in the phase (either way I'm closing this since we now have a larger / more actionable issue to capture this kind of need)
