### ISSUE TITLE
ProposalFieldValue issue

### ISSUE THREAD

**Issue by mortimal1** [PhilanthropyDataCommons/service#119]
proposal version post fails:
{"name":"InputValidationError","message":"Invalid request body.","details":[{"instancePath":"/fieldValues/0","schemaPath":"#/properties/fieldValues/items/required","keyword":"required","params":{"missingProperty":"position"},"message":"must have required property 'position'"}]}

openapi.json specifies the use of "sequence" as required - the table "proposal_field_values" was changed from sequence to position in 0009-alter-proposal_field_values-positions.sql. 

Is it going to be position or sequence?

**Comment by slifty** [comment]
I think @bickelj is in the best position (or... sequence) to resolve this since he worked on #114

**Comment by bickelj** [comment]
@slifty 😆

@mortimal1 The software should consistently use/require "position" in `openapi.json` as well as the database and all intermediate types, validations, and so forth, as of commit 745499dc54cf6f5c17cbc6076a3c871853517ca6. Is it possible the `openapi.json` is outdated still? I can't find the word `sequence` in it at all since that commit. Maybe another `npm run build` is required or update to a later image or `git pull`?

**Comment by bickelj** [comment]
@mortimal1 Is it still giving you trouble?

**Comment by jasonaowen** [comment]
@mortimal1 please re-open this issue if it's still a problem!
