### ISSUE TITLE
Node.js engine versioning

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#134]
We just updated the node engine version ~~for the first time~~ (#133) and that led to a realization that it's probably time to document a policy on when / how the Node.JS version of this project will be updated!  I'm making this issue so we can discuss that policy and ultimately we can just document somewhere in `/docs`

First the easy part: Node releases a new major stable version once a year (the even numbers).  I would recommend that we commit to at least keeping up to date with that.

A more interesting question comes down to whether we should pin to minor / patch versions both in our developer oriented `.node-version` as well as our tests / deploy workflows (we do both right now, so a decision to continue that would just be a matter of deciding when / how those are updated).

The benefits to this are of course around ensuring predictable builds and deployments since things are so closely pinned.  The downside is the additional overhead related to updating our versions manually (it looks like patch releases happen once every two weeks or so).  

Externally the most important decision is related to the value of `.node-version` since we have third parties who are running this software and by specifying a version we're signaling that those third parties should adhere to the version at whatever granularity we indicate there.

We can also, for instance, pin `.node-version` to a major and pin to the reproducable for tests / deployment.

**Comment by bickelj** [comment]
I think this is a fair summary, although I recall updating the node before (after some digging found it in https://github.com/PhilanthropyDataCommons/service/commit/4f55064b1cbdfa12b23d9d7dd568c4adc2ece562).

Updating the node version in most cases should adversely affect no one, including the developers, as the common case will be working code for both the old and new versions. The same should be true for libraries (though less commonly). If an update does cause an adverse effect, the tests or the developers (and in the worst case the users) should flag it.

The benefit to keeping exact versions under source control (top to bottom) is that we know exactly which version combination we tested, can deploy with exactly those versions, can reproduce issues more easily with exactly that version of the deployed artifact, and can have some confidence of how to go in the other direction from binary to source. The repository is more likely to have almost exactly the same software after running the same commands at that same revision.

As for making updates to those exact versions we have not done a great job of keeping up with updates. The updates ideally would be tested as soon as any new version comes out. Any change to a dependency regardless of the declared version numbers is a potentially breaking change. Ideally they would be atomic, one at a time, but that is very cumbersome, so it is easier to do it in batches where at least the only change is to dependent libraries. If something breaks, we can narrow it down. Ideally, also, we could automate some of the dependency updates. I suppose that's what dependabot can do.

As for `.node-version` I am happy with keeping it at major version since it isn't really used for anything beyond documenting which major version this software expects.

A change that definitely can disrupt users is the deployment itself, which causes something on the order of a minute or two of downtime. Maybe that's a separate issue, such as choosing some change time windows.

**Comment by bickelj** [comment]
Something I forgot to mention regarding security is that vulnerabilities often get reported to the software team, are not made public, then the new software release happens, and then the CVE is made known. The way to keep ahead of these kinds of security issues is to speculatively and proactively update to the latest versions prior to CVE publication.

**Comment by bickelj** [comment]
Are we ready for node 18? Why not?

**Comment by slifty** [comment]
> Are we ready for node 18? Why not?

Great call -- I think that our policy should be to always have the project use the `active` version of node (which [would mean 18](https://github.com/nodejs/Release)).  If y'all agree then next step would be to document that policy in the repo and also make the upgrade!
