### ISSUE TITLE
Testing against "Current" node

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#1367]
In https://github.com/PhilanthropyDataCommons/service/pull/1360 @jasonaowen and @bickelj raised some really good points around the value of keeping an eye on the "upcoming" version of Node so that if something big is looming we have a chance to address it proactively before it switches to active and we need to address it reactively.

One idea that I threw out there was instead of doing that test in the context of a PR we might consider a weekly scheduled run of the tests against `Current`.  This way if something changes in `Current` in a way that will impact us (or we add a feature that won't work in `Current`) we know it in a timely manner, but also we decouple that warning from our own active development.

All this is to say...

Let's update our policy to reference the wisdom of paying attention to `Current`, and also add that weekly test against current (which is 23 right now).

(Unless of course folks do feel that PR is the right place to do it, in which case we should still make that improvement but it would be in that action instead)

**Comment by bickelj** [comment]
I'm OK with it either way. The reason to do it as part of the PR is so that the author of the PR can be alerted while the work is fresh and top-of-mind. The reason to do it disconnectedly is so that we don't get distracted by temporary, difficult, or unrelated changes in the node version.

My prediction is that the failures would be few and far between so we'd be best off knowing about them sooner than later. But within a week is probably fine too.
