### ISSUE TITLE
Add ability to retrieve deep associations

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/service#174]
The API currently returns only one level of requested objects. E.g., `/proposals` returns a list of proposals, but without any associated objects nested within. (The Swagger documentation about nesting `versions` is not accurate.)

So if, for example, you want all the field data associated with the most recent version of a proposal, you have to make many sequential calls to the API. That's fine as the default behavior, but in real-world use, API consumers are greatly advantaged by being able to opt in to including some of the nested associations as part of a single call. In the above example, the proposal would be returned with the application form fields already included.

We need to determine the preferred ergonomics of this. For instance, are our needs for each endpoint obvious enough that a simple boolean (`deep=true`) only has one reasonable outcome? Or do we need a query param language for the API consumer to request specific related objects (`include=proposalVersion,applicationForm,applicationFormField`)? Etc.

**Comment by bickelj** [comment]
> We need to determine the preferred ergonomics of this. For instance, are our needs for each endpoint obvious enough that a simple boolean (`deep=true`) only has one reasonable outcome? Or do we need a query param language for the API consumer to request specific related objects (`include=proposalVersion,applicationForm,applicationFormField`)? Etc.

Having a simple `deep=true` might be confusing because it raises the question "how deep?" If I were to set `deep=true`, I might expect it to be fully deep. For example, I might expect `GET /applicationForms?deep=true` to return all the way through to and including canonical fields.

A simple `shallow=true` would be unambiguous: it always returns only the direct attributes of the entity.

The principle I used in https://github.com/PhilanthropyDataCommons/service/pull/157 up through b71998d was to return to a `GET` call the same depth as was expected in a `POST` call (plus the wrapping list). We probably agreed earlier to keep it shallow in some discussion several weeks/months ago and then yesterday @slifty made the same suggestion on `GET`.

A compromise might be that the default is the shallow, direct attributes of the entity, but there is a boolean parameter to suggest "same depth as POST." I don't have a great name for that other than `returnSameDepthAsPost=true|false`.

**Comment by reefdog** [comment]
> Having a simple `deep=true` might be confusing because it raises the question "how deep?"

Right. I would only suggest we consider this if we determine it's actually unambiguous once we are implementing. (I assume that's _not_ the case, but keep reading…)

> A simple `shallow=true` would be unambiguous: it always returns only the direct attributes of the entity. […] A compromise might be that the default is the shallow, direct attributes of the entity…

I would agree that `shallow` should be the default. I see  what you mean about a `GET` returning the same hierarchy expected by a `POST`, but I don't think that's a necessary or intuitive default. (Keep reading…)

> but there is a boolean parameter to suggest "same depth as POST."

Two things here:

1. It's not uncommon for `POST` response to contain the newly-created object (along with whatever status codes). This would be a sensible place to default to this "same as `POST` request structure" response format, since it essentially lets the user spot-check that all relevant operations/associations were performed.
2. I don't have a use case for when we'd want `GET?returnSameDepthAsPost`, but if we do ① anyway, then presumably it would be trivial to add.

> One thing I don't think we should do is allow a variety of depths. We should choose a sensible depth (whether "same as POST" or "full depth") for an entity and allow the shallow option.

Collating the suggestions, I think a sensible path is:

- Default to `shallow` (no param necessary) for `GET`
- Return `POST`-like structure as the response to `POST`, and optionally for `GET?returnSameDepthAsPost`
- Either of these:
   - A "full-depth" hierarchy for `GET?deep` if we determine calls have unambiguous depth
   - Something more complicated like indicating which associations we want from an approved list for each endpoint — **This is the one I understand you don't want, but I'm not sure how we avoid it if `deep` is ambiguous?**

**Comment by bickelj** [comment]
I agree that whatever does a POST should see the full object at the same depth in the response. I think that currently happens with `/applicationForms`. If not, we should fix it.

Suppose we use the unambiguous default `shallow=true` but if the caller wants the more ambiguous "some sensible depth" option set `shallow=false`. Would that solve it?

**Comment by bickelj** [comment]
> I don't have a use case for when we'd want GET?returnSameDepthAsPost, but if we do ① anyway, then presumably it would be trivial to add.

Looking more closely, this is likely a false presumption because the insert code would use a different technique than the select. Then again that might be premature optimization on my part to prefer a single query to return all my results, however deep.

**Comment by bickelj** [comment]
Sorry for the piecemeal disjointed replies. I'll try to summarize my response and suggestion more clearly here.

> Default to shallow (no param necessary) for GET

Yes.

> Return POST-like structure as the response to POST.

Yes.

> optionally for GET?returnSameDepthAsPost

Nevermind that one. Instead, the caller sets `shallow=false` to get the same effect I was looking for with the awkwardly named `returnSameDepthAsPost`. The depth would end up being the same depth, because the depth for post was a sensible depth, and that same sense drives the non-shallow GET.

**Comment by reefdog** [comment]
We're mostly iterating toward agreement, which means it's time for fresh eyes to come in and upset the apple-cart! Paging @gmurtaza00 and @slifty, lol.

> the caller sets `shallow=false` to get the same effect I was looking for with the awkwardly named `returnSameDepthAsPost`.

I would vote hard against the specific semantics of `shallow=false`, which is a bit like ordering `/coffee?black=false`. API consumers need a menu, even if there's only one additional item on it, and they should request it by name (`/coffee?fancy=true`) for future-proofing, if nothing else. (It would also be great if we can offer arbitrary combinations such as `/coffee?cream=3&sugar=2&flavors=hazelnut,frenchVanilla`, but that's the difficult path and can be decided separately.)

So that's an argument _for_ something like `returnSameDepthAsPost`, even if we need a better name. `postResponseFormat` perhaps?

> The depth would end up being the same depth, because the depth for post was a sensible depth, and **that same sense drives the non-shallow GET**.

Responding to the bold part specifically: I don't find that coupling intuitive. Of course a `GET?returnSameDepthAsPost` (or `GET?postResponseFormat` or whatever) should use that depth, that's inherent in its name. But we still _might_ need a different response as well and I think we should remain open to the possibility.

I'm fine waiting until implementation to determine whether that's the case, though, and starting with `returnSameDepthAsPost/postResponseFormat`.

**Comment by bickelj** [comment]
My favorite proposal is still the one in https://github.com/PhilanthropyDataCommons/service/pull/157/commits/b71998d27a8ae5a516badec6678af6ffa6b23b49. It has exactly one menu item, no query params needed. But if we can figure out the name of the query parameter that indicates the same root reason we chose something other than a shallow/simple post format, I'm up for that too. In other words, it's not because "post did it that way" that we would request the same depth as post, it's "whatever reason drove us to make POST do it this way is also a good reason to make GET do it this way." That's true for `/applicationForms`, at least. I don't think there are multiple ways to POST to `/applicationForms` nor do I think there ought to be.

**Comment by bickelj** [comment]
As for the parameter name, I'm starting with `includeFields=true` for `/applicationForms`. I think I'd prefer a sort of API-wide parameter name rather than different ones per entity but there are advantages and disadvantages to each approach (and cannot think of a non-specific one that satisfies).

**Comment by slifty** [comment]
This behavior is now the default, so closing the issue!
