### ISSUE TITLE
How to include metadata in the API response

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/service#175]
Currently, our API returns requested objects as the top level of the response. That is, a call to `/applicants` returns an array of applicants as the response body, and a call to `/applicants/{id}` returns the applicant object as the response body.

As the dataset grows and we have to support things like pagination, there are going to be request metadata useful to an API consumer, e.g. number of total objects, number of objects in the _current_ response, number of batches available, position of current batch, timestamp of most recent object change, etc.

We could perhaps include these in the HTTP headers, but a common format is for the JSON response body itself to return an object like this:

```json
{
	"applicants": [],
	"metadata": {}
}
```

While we don't need to tackle the specifics of metadata now, I _do_ think we should consider the syntax, because if it's going to be part of the response body, then we should at least go ahead and start returning the primary response in this format so API consumers don't have to adjust painfully later.

**Comment by bickelj** [comment]
My initial thought is this: can we avoid such a metadata object in the responses? For pagination, for example, can it not be handled with a pair of query parameters `?lastId=42&count=50`? The size of the table may be changing with each request, so your last response might include out of date information. Same for the most recent object change. Now the response body is changing and out of date because we included additional state, etc. The count of objects in the current response can be had by `applicants.length`. Perhaps there are other mechanisms to communicate metadata, such as a metadata endpoint for each entity, like `/applicants/metadata` which give a snapshot of minimum id, maximum id, count, last modified, etc. That and/or use of HTTP headers.

All that said, if there are common libraries out there that expect such an object, that it will be inevitable, and it makes life much easier, I agree it would be better to add a `metadata` key sooner than later.

**Comment by reefdog** [comment]
I like the idea of not needing to attach metadata as a separate object on the same response. I also like your suggested syntax for pagination ("here's the last item you sent me, and how many I want after that").

I don't know of any libraries that assume a `metadata` object be returned, it's just a syntax I've seen in the past. And if that pagination style is achievable, then I think the only metadata I personally need would be total object count, which could either be available at an endpoint or HTTP header.

All this to say: good points, +1!

**Comment by reefdog** [comment]
> I also like your suggested syntax for pagination ("here's the last item you sent me, and how many I want after that").

I'm realizing `?lastId=42&count=50` limits us to nothing but "give me the next `count` results, which isn't sufficient for a true pagination interface, where we'll also need to go backwards and target a batch of results that aren't contiguous with the last requested batch. (I.e., from page 1 I might want to skip to page 10.)

This isn't relevant to the `metadata` conversation, though, so I'm going to split it off to a new ticket.

**Comment by slifty** [comment]
We now have a `bundle` object which is where this sort of metadata is returned.

There is some improvement to be made (see #895) but I believe this issue is addressed in the meantime, as evidenced by pagination support!
