### ISSUE TITLE
Paginate API results

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/service#179]
_Note: This is essentially a performance optimization and can wait until we need it. I'm opening it anyway to capture a conversation that started in another ticket._

@reefdog in https://github.com/PhilanthropyDataCommons/service/issues/175#issue-1497031419:
> As the dataset grows and we have to support things like pagination, there are going to be request metadata useful to an API consumer, e.g. number of total objects, number of objects in the current response, number of batches available, position of current batch, timestamp of most recent object change, etc.

@bickelj in https://github.com/PhilanthropyDataCommons/service/issues/175#issuecomment-1351986273:
> For pagination, for example, can it not be handled with a pair of query parameters `?lastId=42&count=50?`

@reefdog, after [initially liking the idea](https://github.com/PhilanthropyDataCommons/service/issues/175#issuecomment-1353336191), in https://github.com/PhilanthropyDataCommons/service/issues/175#issuecomment-1353402688:
> I'm realizing `?lastId=42&count=50` limits us to nothing but "give me the next `count` results", which isn't sufficient for a true pagination interface, where we'll also need to go backwards and target a batch of results that aren't contiguous with the last requested batch. (I.e., from page 1 I might want to skip to page 10.)

Our pagination syntax should allow indicating the **starting position** and the **batch count**¹. The API consumer should already know the **total object count**, and ideally this would be returned on every call anyway (either as an HTTP header or a `metadata` sidecar object, TBD in #175), since it may change between calls.

The order of the results should always be consistent between calls; that is, using a stable default order when none is specified so that unless underlying data change, repeated calls to `?start=100&count=50` always return the same 50 objects.

(I don't think we need to worry over-much about inconsistencies caused by new data having arrived in the system since the last request. If the API consumer requests `?start=100&count=50`, and then the database receives 10 new objects inserted at position `0`, and then the API consumer requests `?start=150&count=50`, then the first 10 results will be the last 10 from the previous call. I think that's acceptable.)

----

¹This is really more of a batch _maximum_ since, at the end of the result set, the API may return less than an entire batch.

**Comment by bickelj** [comment]
@reefdog Blast. You're right: true pagination requires a bit more than those two.

**Comment by bickelj** [comment]
How should we paginate when using UUIDs (#72)? Order by created date? Order by UUID?

**Comment by reefdog** [comment]
Yes, we would need to order. (I would suggest we always impose an order, just so the results are… deterministic? Is that the right term?) I'm not picky about _how_ we order, just _that_ we do. Created date, ascending, seems reasonable.

At some point we'll likely want to let API consumers request a specific sort order / direction, but we'd still have our own default when none was requested.

**Comment by reefdog** [comment]
(I should also clarify that `start` in my example was meant as a **position**, not an ID.)

**Comment by bickelj** [comment]
That all makes sense, yes.

**Comment by reefdog** [comment]
> I'm not picky about how we order, just that we do.

I should relax this position. Perhaps we only need to order when certain request conditions are met: explicit order requested (not currently implemented/designed), or implicit default order triggered (such as via the pagination-related params here in this issue).

**Comment by slifty** [comment]
On a separate note: in terms of information back FROM the server I wanted to share this SO question -- https://stackoverflow.com/questions/12168624/pagination-response-payload-from-a-restful-api

In short, it will be useful to include pagination data in the server response as part of the HTTP headers (since it is metadata about the response rather than being actually part of the response).

**Comment by slifty** [comment]
In terms of input -- I would suggest we not try to re-invent pagination in REST apis, and root our design in other major APIs and what they have done (obviously tweaking based on our needs).

For example, Github's pagination parameters seem pretty fine: https://docs.github.com/en/rest/guides/using-pagination-in-the-rest-api?apiVersion=2022-11-28

`page=X`
`perPage=Y`

(though I suppose by anchoring by ID we might be able to avoid a race condition where an item is inserted between queries.)

**Comment by jasonaowen** [comment]
I don't have a strong opinion on headers vs metadata in the body. I'll note that the [FHIR](https://en.wikipedia.org/wiki/Fast_Healthcare_Interoperability_Resources) specifications have a pretty robust section on [search, sorting, and pagination](https://www.hl7.org/fhir/search.html#return), and I remember being impressed a few years ago - they've clearly thought it through!

**Comment by slifty** [comment]
Oh that's great -- will dig in!

Also so folks know I rose my hand to take on implementing pagination!

**Comment by slifty** [comment]
I dug into the FHIR specification that @jasonaowen mentioned above and wanted to translate what I learned into some options for initial implementation:

1. General parameters are prefixed with `_` (e.g. `_count` would be used to indicate how many items per page)

2. There is no publicly documented concept of pagination, rather, the return value of a given set would provide four links that the server commits to understanding: `next`, `previous`, `first`, and `last`.  The server might choose to use something like `page` as the parameter, but the client would not be able to rely on this / it wouldn't be a documented part of the API.

One thing that the FHIR uses is the concept of a `Bundle` object which is a root level object returned by REST endpoints.  This object could have a wide range of metadata associated with it (e.g. total counts, the various pagination links, and a list of objects associated with a given query based on various `_include` parameters).

(Side note: FHIR does also define a pattern for specifying what kinds of objects to include in a set, which I do think we might want to consider adopting.  This would mean instead of a `includeDeepFoo` boolean we would take a list of related object types that should be returned).

---

Some decisions:

1. Should we formally define `_page` as a parameter (FHIR does not, but we could), or should we just return the `next` / `prev` links.

2. Should we create a wrapper object (e.g. `Bundle`) or should we define bundle metadata as a header.

FHIR does return a bundle but it actually treats a bundle as a resource type in itself.  There is an argument for putting metadata about a given response in HTTP headers insofar as the metadata is not actually part of the resource representation, but there is also an argument that we should include it in the response body / it will be more intuitive and easier to work with for clients that way.

**Comment by slifty** [comment]
Some decisions!

1. We will use `_page` (which allows a UX to predictably create links to pages)
2. We will use the concept of a root level `Bundle` type that will be returned any time a collection of objects is returned by any endpoint.

The `Bundle` concept may end up feeling wrong somehow, and we should feel comfortable revisiting it.  It does mean that a REST call for resource "X" returns a Bundle instead of an array of X, which is slightly awkward, but we're betting on that being a worthwhile trade.

**Comment by jasonaowen** [comment]
Thanks for researching, documenting, and following up with this, @slifty!

**Comment by jasonaowen** [comment]
After playing with this in practice, I think the flexibility of `count` + `offset` might be more useful than the predictability of `count` + `page`. I think ideally the API would be able to take those and return a list of pages in the bundle. For example, when there are 50 proposals, here is the very rough shape of what I'd hope for:

```
GET /proposals?count=20&offset=40
{
  "total": 50,
  "pages": [
    "/proposals?count=20&offset=0",
    "/proposals?count=20&offset=20",
    "/proposals?count=20&offset=40",
  ],
  contents: { ... }
}
```

And, if I could make wild wishes,

```
GET /proposals?count=40&offset=10
{
  "total": 50,
  "pages": [
    "/proposals?count=10&offset=0",
    "/proposals?count=40&offset=10",
  ],
  contents: { ... }
}
```

...but feel free to push back on that one.

Either way, I think the list of page URLs is pretty important - it's hard to do pagination without knowing how many pages there are!

**Comment by slifty** [comment]
You'd be able to know how many pages there are by knowing the total and dividing that by the count (and be able to generate the URLs pretty easily).

Could you expand a bit more about the benefit of the server providing pages?  The server would have the same information as the client and would implement the same algorithm a client could.

If there are 50,000 proposals would you imagining the API would be returning 2500 separate page entries?

I'm fine with replacing page + count to offset + count regardless.

**Comment by jasonaowen** [comment]
Hm, that's a good question!

I was trying to follow [HTTP As The Engine Of Application State](https://en.wikipedia.org/wiki/HATEOAS) principles, but you point out what happens when you follow that too far. [Apparently](https://stackoverflow.com/a/23942028), the common solution is URI templating, which I wasn't aware of! The client still needs to construct a URI, but is doing so with guidance from the API, rather than encoding that knowledge into the client.

Maybe this is not an important distinction, and this level of coupling is acceptable.

**Comment by reefdog** [comment]
>  Is there a use case for needing to jump to a specific page number?

Our pagination design allows it, albeit without expressing it as "jump to page x":

https://user-images.githubusercontent.com/4731/230539108-23c213f1-e7fb-4dc4-9d8b-21f43c060cb9.mov

**Comment by jasonaowen** [comment]
Now that we're returning deep proposal data (#274), the response to `/proposals` can be large - in the megabytes. A user has reported that trying to use the Swagger docs with the default values (of `_count=100`) leads to the page hanging, presumably as Swagger parses and formats multiple megabytes of JSON. We should probably lower the default to a more reasonable value!

The front-end is [overriding the default value anyway](https://github.com/PhilanthropyDataCommons/data-viewer/blob/2cd0f6c324942ec170be54285a40389e379e78da/src/pages/ProposalList.tsx#L52).

**Comment by slifty** [comment]
@jasonaowen would you be up for opening a separate issue for that?  I'd like to avoid this being a monolithic ticket (and I think we should probably close it as complete and open pagination tickets for specific endpoints at this point)

**Comment by slifty** [comment]
(Nevermind, I opened!)

I'm also going to mark this as closed.
