### ISSUE TITLE
Dependabot frequency and scope

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#241]
I think we're getting a LOT of dependabot notifications -- more than just security updates.

I'd like to suggest we avoid updating versions of our dependencies unless either:

1) The update is needed for our development goals (e.g. we organically find them)
2) The update offers a security patch

Rooted in this is that there is a cost to updating in the form of developer attention as well as potential introduction of impact on working functionality in our system / need for refactoring.

To resolve this I would suggest we change our dependabot behavior by:

1. Disabling dependabot generally
2. Enabling dependabot alerts
3. Enabling dependabot security updates

<img width="799" alt="image" src="https://user-images.githubusercontent.com/208884/221249046-5f682abb-f19d-4717-ab35-2569d9748973.png">

I believe this is the approach most projects I've seen has taken, and I think will result in a kinder experience for us.

**Comment by bickelj** [comment]
I advocate keeping the current configuration for the following reasons:
1. We cannot easily tell when an update includes a security update until after the security vulnerability gets published. Staying on top of updates helps avoid getting in the situation of needing an urgent security update.
2. It is low cost to merge these updates thanks to dependabot. It takes a couple of minutes here and there to review and merge. Since February 1 I have spent a grand total of one and a quarter hours on dependency updates (16 total updates).
3. If we wish to cut down on distracting emails, we can set up email filters to send dependabot notices into a different folder.

**Comment by jasonaowen** [comment]
This gets into vision and scope a bit, which I don't yet have a strong understanding of. Turning off dependabot would be some intentional technical debt, and I'd want for such a proposal to include the timing and circumstances for turning it back on and bringing dependencies back up to date. As with taking on any technical debt, that will result in more total work in order to save some time now - and that might be the right thing to do, although it makes me uneasy.

I agree with everything @bickelj wrote. In particular, I think we can reduce the cost of merging! Since we're not in production yet (right?), we can kinda YOLO the dependabot PRs - glance through them, check that CI is passing, and just merge them without going through a heavy review process. Would that address your concern about time spent, @slifty?

**Comment by bickelj** [comment]
@slifty I acknowledge this, though:
> potential introduction of impact on working functionality

I haven't seen this happen yet, but I haven't been done much manual testing of the service, either. Have you seen some of these impacts yet that were not caught by automated tests or automated deployment?

**Comment by slifty** [comment]
Thank you both!  This is fine, and I'll probably go on to adopt it on some of my other projects.

Honestly it seems to me we're OK with time spent based on Jesse's earlier reply so I'm totally fine -- I just wanted to ask in case.  Maybe some day the "time spent" will get large enough that we want to revisit (though I think dependabot also provides levers to help with that -- e.g. "don't open more than X PRs in a given time period").

Would folks be OK with me turning on alerts?  I think it's somewhat moot since we're merging a larger swath, but it might help flag when there's a particularly critical PR out there (or if a tool has a flaw with no current fix and we might consider moving away from it).

Side note I wish github notifications would let me filter -- I use it rather than email and boy does it get noisy (but that's a me / github problem!  Pay no heed!)

I'll close this, thanks again all.

**Comment by slifty** [comment]
Oh and sorry I missed your question @bickelj 

> Have you seen some of these impacts yet that were not caught by automated tests or automated deployment?

Not in this project!  I just know that in the past upgrading tools has sometimes led to unexpected behavior on other projects.  That said, those projects were often legacy projects with (1) not great test coverage and (2) ... very old dependencies that weren't kept up to date over time ;) ;) ;)

Bottom line, we're good!

**Comment by bickelj** [comment]
@slifty said:
> Would folks be OK with me turning on alerts?

Sure, that sounds great!

>  I wish github notifications would let me filter

Oh! I had not even considered that! It looks like I have hundreds of unread notifications in the github interface. I had assumed you were talking about email, my mistake!
