### ISSUE TITLE
Search capability for proposal data

### ISSUE THREAD

**Issue by bickelj** [PhilanthropyDataCommons/service#277]
The ability to search within proposal field values has been suggested as an initial search capability.

We envision search to have (at least) two new components in the implementation:
1. Use/configuration of [postgresql search](https://www.postgresql.org/docs/14/textsearch.html).
2. Endpoint(s) in the API to perform the search queries.

**Comment by jasonaowen** [comment]
For the first draft, we'll be okay with low [recall](https://en.wikipedia.org/wiki/Precision_and_recall) results - that is, it's more important to get some kind of search working that we can then iterate on, rather than spending time and effort preemptively maximizing the number of relevant search results found.

During today's call, @jim-mcgowan confirmed that - again, at least for a first iteration - it would be okay for multi-word search queries to *not* return proposals that had one search term in one field and another in another field. For example, if the search were "children climate", it would be acceptable for a proposal that had the fields "Organization Name: Children Prosperity Endowment" and "Proposal Title: Countering Climate Change" to not be returned in the search results, but a proposal that had the field "Proposal Title: Children and Climate Change" would be returned.

That suggests that we only need a single full-text-search index on `proposal_field_values.value`, plus the database queries to find it and the API endpoints/parameters to parse the request and return results. I'd suggest adding a `q` parameter to `/proposals`, so like `/proposals?q=children+climate` for the earlier example.

Finally, as @bickelj alluded to, [PostgreSQL Full Text Search is Good Enough](https://rachbelaid.com/postgres-full-text-search-is-good-enough/). Later we might decide that we need much deeper search functionality, and at that point we can reconsider our approach and evaluate Apache Solr or Meilisearch or whatever, but for now let's just use the very powerful tools we already have!

**Comment by jasonaowen** [comment]
Another recent how-to post and discussion I saw recently, which I hope will be helpful: [PostgreSQL Full Text Search is better than...](https://admcpr.com/postgres-full-text-search-is-better-than-part1/) and [Reddit discussion](https://www.reddit.com/r/PostgreSQL/comments/12u30a7/postgres_full_text_search_is_better_than/).

**Comment by slifty** [comment]
Resolved by #320
