### ISSUE TITLE
Readme should explain what has to be done to set up authn

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#290]
The current README instructions don't result in a working local copy of this project -- in particular, the copy I have set up won't allow any API calls due to a lack of auth service without some further setup in my local environment

I believe KeyCloak is our officially recommended tool for the project, so I'd like to suggest we re-visit including some steps for how to set up KeyCloak auth.  We don't want to write keycloak documentation, of course, so I imagine this would mostly take the form of:

1. linking to the appropriate KeyCloak docs
2. indicating what byproducts of the KeyCloak set up should be written to various environment variables
3. indicating any additional specific keycloak setup steps need to be performed (and how the outcomes of those steps map to our API calls)

An important note:  I know that KeyCloak is not intended as our only auth vendor, and we should mention that folks can set up alternative auth if they choose to, but that shouldn't stop us from providing instructions -- and the reality is that KeyCloak *is* our recommended tool for this project.

**Comment by bickelj** [comment]
I found in a local branch (thankfully I saved it) these instructions, they're a little out of date because they include some extra steps regarding authorization. To minimize environment variables we dropped one, `AUTH_SERVER_JWKS_URI` which I think we should add back at some point when needed (same with authorization). You can skip the roles/groups. I just thought I'd post this here so that the information is out there and also to help us figure out where it should go.

Again, the roles parts are out of date because we decided to start with authentication first and tackle authorization later.

### Authentication and Authorization

A valid Bearer JSON Web Token (Bearer JWT) is required in requests to the PDC service. The exception is the API documentation page. These environment variables configure the expected realm and JWKS issuer keys:
- `AUTH_SERVER_ISSUER`: the URL for the issuer (this is the "realm" URL in Keycloak terminology).
- `AUTH_SERVER_JWKS_URI`: the URI for this service to get the JSON Web Key Sets (JWKS) to validate the signature of the Bearer JWT against the public key of the issuer. Set this to `${AUTH_SERVER_ISSUER}/protocol/openid-connect/certs` if Keycloak is your auth service.

The PDC service assumes there will be three roles in the JWT with ascending levels of privilege, named `pdc-viewer`, `pdc-user`, and `pdc-admin`, respectively. These are expected inside an array with key `roles` in an object under key `realm_access` in the JWT object. In other words, for a JWT named `jwt`, there is an array at `jwt.realm_access.roles`.
* A user having role `pdc-viewer` can read data with `GET` requests.
* A user having role `pdc-user` inherits the `pdc-viewer` role and can also write to most endpoints with `POST` requests.
* A user having role `pdc-admin` inherits the `pdc-user` and `pdc-viewer` roles and can also `POST` to all endpoints.

#### An example with a Keycloak authentication and authorization service

From the Keycloak admin interface, e.g. https://my-host/admin:
1. Add a realm e.g. "pdc" (avoid spaces in the name).
2. Within the realm just added in step (1) add a client e.g. "pdc-service", with Client authentication off and Authorization off:
    - Standard flow unchecked,
    - Direct access grants unchecked,
    - Implicit flow unchecked,
    - Service accounts roles unchecked,
    - OAuth 2.0 Device Authorization Grant (optional), and
    - OIDC CIBA Grant unchecked.
3. In the settings for the client added in step (2), set the root URL and Home URL to the URL of the PDC service (not the auth service). Add redirect URIs:
    - `/applicants/*`
    - `/applications/*`
    - `/applicationForms/*`
    - `/canonicalFields/*`
    - `/proposals/*`
    - `/proposalVersions/*`
4. In the settings for the client added in step (2), add a Web origins of `+`.
5. Within the realm added in step (1), add three roles: `pdc-viewer`, `pdc-user`, and `pdc-admin`.
6. Within the role settings for `pdc-user`, add associated role `pdc-viewer`.
7. Within the role settings for `pdc-admin`, add associated roles `pdc-user` and `pdc-viewer`.
8. With in the realm, add a user, e.g. `test-user`.
9. To the user added in step (8), add the role `pdc-user`.
10. Log in as the test user.
11. Find the JWT (e.g. in browser dev tools).
12. Add the JWT value to the `Authorization` header with value `Bearer [the token]` for a separate request to the back end.
