### ISSUE TITLE
Implement GET /opportunities by Application Form ID

### ISSUE THREAD

**Issue by bickelj** [PhilanthropyDataCommons/service#322]
This feature was requested by a user of the API.

**Comment by slifty** [comment]
For now I think it would be reasonable to mark this as wontfix -- the reason is that if you have an application form ID you can load the application form, which provides the opportunity ID, which you can then load the opportunity by directly.

That isn't to say this feature would never be implemented, but it strikes me as a low priority at this moment without more context around why the above is not a good enough solution.
