### ISSUE TITLE
Compress API response

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/service#329]
Our API server doesn't seem to be compressing/gzipping the JSON response. It's worth looking into what it would take to enable this. (I don't think we should lean entirely on pagination to reduce our payload when gzipping is fast and well-supported, and JSON is a great candidate for it.)

**Comment by bickelj** [comment]
If I recall correctly, using compression weakens TLS. But maybe that's all been mitigated in servers/proxies recently.

**Comment by slifty** [comment]
@bickelj some quick googles didn't reveal the source of that concern for me, would you be able to provide some references for us to consider the tradeoffs?

I do see [this article](https://www.linkedin.com/advice/0/how-do-you-test-measure-impact-tls-compression) about *TLS compression* having a potential vulnerability, but I'm not sure if that's what justin is talking about.

**Comment by bickelj** [comment]
There is TLS compression and there is HTTP compression, but my understanding is that either is/was vulnerable.

https://en.wikipedia.org/wiki/BREACH
https://en.wikipedia.org/wiki/Transport_Layer_Security#CRIME_and_BREACH_attacks

I see some more recent github issues where `testssl.sh` (great tool, btw) will show vulnerability to the same. So unless there is some evidence that this issue has been mitigated or resolved in later versions of TLS or later versions of `nginx` I think we have to assume it's still there.

**Comment by slifty** [comment]
Amazing stuff!  Thanks for raising it.

**Comment by bickelj** [comment]
> Does the potential risk affect us? We aren't using cookies for authentication, right?

I think we should assume we are potentially affected. I think Keycloak does use cookies, but it seems like a generalized attack, so we could guess other headers besides cookies could be recovered.

> Is everyone else just throwing caution to the wind?

Probably. Or the attack may not be so easy to mount. Or it might be more of a cost analysis.

So I don't bring up the issue to say "we definitely should not enable compression" just that this is one reason we might not want to. If we aren't susceptible, if it's hard to do the attack, or if there's some easy mitigation besides losing out on compression I'm all for enabling compression.

**Comment by bickelj** [comment]
I learned this later but forgot to mention it: the BREACH attack is more of a browser-side attack.

**Comment by bickelj** [comment]
According to the [heal the breach paper](https://ieeexplore.ieee.org/document/9754554):
> To be successful with the BREACH attack, the following quite common situations must be met at the server:
>
>    The server must use HTTP compression.
>
>    The website must reflect user-input in HTTP response body.
>
>    HTML code must include a secret token that could be used to impersonate the victim.
>
>    Also, some known prefix needs to be known to help bootstrap compression.

On the face of it, I don't think we meet the condition "The website must reflect user-input in HTTP response body." But what about use input in the headers? Or does "397" appearing in the response of `GET /proposals/397` count? Hmm.

**Comment by jasonaowen** [comment]
> HTML code must include a secret token that could be used to impersonate the victim.

I don't think we meet this criteria? We're not doing any CSRF, and tokens come from Keycloak rather than the application.

**Comment by jasonaowen** [comment]
> Depending on what that means, I would assume that "a javascript library holds a JWT that it uses to send requests to the backend" would count. :frowning_face:

Can you walk me through your reasoning there, @bickelj? That does not match my understanding.

> Question: how do others deal with this? Don't most major tech orgs with APIs support compression?
> 
> I ask this just because I am inclined to believe that if something is secure enough for, say, Google it'd be secure enough for us.

Yes, I am leaning towards "even if this were a security risk that affected us, the performance improvement is still worthwhile.

**Comment by bickelj** [comment]
> Can you walk me through your reasoning there, @bickelj? That does not match my understanding.

Thanks for the push-back. My basis for the above comment was a general sense of "if we do not have a clear and evident reason to believe that we are invulnerable to the attack we should err on the side of assuming we are vulnerable." I now have watched [the original presentation of BREACH](https://invidious.kavin.rocks/watch?v=CoNKarq1IYA) and [a follow-up presentation](https://invidious.kavin.rocks/watch?v=T4iTwNLPv4g) to get a better sense of the attack.

Here is my better understanding regarding the "HTML code." Because the headers are not compressed (this is HTTP compression, TLS compression is verboten these days) and the attack works with HTTP compression of the body, the attack requires something sent to the server to be reflected back in the body proper (not headers). So the author by "HTML code" probably means "something in the response body." But that's a repetition of "The website must reflect user-input in HTTP response body" so the author there might be mistaken on the "HTML code must include a secret token that could be used to impersonate the victim" bit. If there is any data from the request reflected in the response body, e.g. `"&_content=Bickel"`, then it is still conceivable that the technique could work (assuming all the other prerequisites are met), right?

**Comment by bickelj** [comment]
> I ask this just because I am inclined to believe that if something is secure enough for, say, Google it'd be secure enough for us.

"Google does it" is less than convincing for me. Google is in a much different position than us. They would have a much larger impact on their power and network bills by enabling HTTP compression and they have many more engineers to potentially mitigate on the application side. The business model of Google is to violate confidentiality in the first place, too.

**Comment by reefdog** [comment]
I think caution and questioning crowd movement is good, and I appreciate that take.

That said, we can flip the burden of proof around to look for examples of platforms that _aren't_ compressing due to the security risks. Google (and AWS, and Cloudflare, and…) are also a platform and have SLAs to uphold and plenty of litigious customers to keep safe.

**Comment by jasonaowen** [comment]
I think there are two mitigations here which make the risk of enabling compression low enough to justify.

First, the method of this attack requires the attacker to be able to cause an authenticated user to make arbitrary requests with their credentials. I believe the data-viewer in particular, and our authentication method in general, prevent that - or at least shift the risk so that this particular attack is not relevant. Browsers do not have first-class support for `Authorization: Bearer <token>`-based authentication, so requests must be made via JavaScript, which must inject the header - the browser doesn't do that for us, the way it does with cookies. If the attacker can induce the browser to make an arbitrary request using the token, then they're running arbitrary JavaScript on the user's browser that is able to retrieve the token, in which case they could just exfiltrate the token: they've already won.

Second, the primary risk of this attack seems to be session hijacking, where attackers gain control of credentials sent in the response body. Our API does not issue credentials - including cookies - and so enabling compression on the API would not risk session hijacking.

**Comment by bickelj** [comment]
I ran `testssl.sh` against our API and surprise: compression is not disabled. What I mean is that the documentation assets have compression enabled, so it's not like nginx has compression disabled nor like express has compression disabled. I see we haven't disabled TLS 1.0 or TLS 1.1 yet, so I will do that now.

> the method of this attack requires the attacker to be able to cause an authenticated user to make arbitrary requests with their credentials.

I don't think that's true. The attacker must be able to observe the encrypted traffic having the secrets the attacker is interested in and be able to send requests from the victim's browser.

What if we take a step back and ask the question: what problem are we solving by using compression? If the problem is we are sending megabytes of data and displaying kilobytes, perhaps there is a way we could request kilobytes instead, for example.

**Comment by jasonaowen** [comment]
> I ran `testssl.sh` against our API and surprise: compression is not disabled. What I mean is that the documentation assets have compression enabled, so it's not like nginx has compression disabled nor like express has compression disabled.

That is relevant information! Glad there's no blockers on the hosting setup. We'll need to [opt in via the `compression` middleware](https://stackoverflow.com/a/46391374) in the application.

> I see we haven't disabled TLS 1.0 or TLS 1.1 yet, so I will do that now.

Excellent call. Forking that discussion to https://github.com/PhilanthropyDataCommons/service/issues/353.

> > the method of this attack requires the attacker to be able to cause an authenticated user to make arbitrary requests with their credentials.
> 
> I don't think that's true. The attacker must be able to observe the encrypted traffic having the secrets the attacker is interested in and be able to send requests from the victim's browser.

I don't understand the distinction you're making between "cause an authenticated user to make arbitrary requests with their credentials" and "send requests from the victim's browser"; can you say more?

> What if we take a step back and ask the question: what problem are we solving by using compression? If the problem is we are sending megabytes of data and displaying kilobytes, perhaps there is a way we could request kilobytes instead, for example.

Yes, pagination is also on the to-do list, but compression is a standard performance improvement that reduces network traffic. Proposal data compresses well; one example goes from 24k to 6.7k, which is a 71% reduction. Enabling compression should speed up every page on the site, not just the currently-unoptimized full proposals list request.

**Comment by bickelj** [comment]
>  If the attacker can induce the browser to make an arbitrary request using the token, then they're running arbitrary JavaScript on the user's browser that is able to retrieve the token, in which case they could just exfiltrate the token: they've already won.

In the case of PDC, I think you are probably right. If they try to send an unauthenticated request to PDC, they will continue to get back 401 regardless of parameters, therefore the response body will not have any secrets in it and will not vary with those parameters.

Thanks for your patience and reasoning through it with me.

**Comment by bickelj** [comment]
> That is relevant information! Glad there's no blockers on the hosting setup. We'll need to [opt in via the compression middleware](https://stackoverflow.com/a/46391374) in the application.

Since my earlier post, I found that the existing nginx configuration has compression for some mime types but not others. Enabling it is simple enough within the reverse proxy. I assume nginx is going to be faster at doing compression than express so I think the configuration change in nginx is enough for now.

**Comment by bickelj** [comment]
Better TLS and compression for `application/json` now live.

```
$ diff proxy.conf proxy.conf.old20230512 
10,15d9
<     ssl_protocols TLSv1.2 TLSv1.3;
<     ssl_prefer_server_ciphers on;
<     ssl_ciphers 'DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:TLS_AES_128_GCM_SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-CHACHA20-POLY1305:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256';
<     add_header Strict-Transport-Security "max-age=31536000" always;
< 
<     gzip_types application/json text/plain text/css application/javascript text/xml application/xml+rss;
37,40d30
<     ssl_protocols TLSv1.2 TLSv1.3;
<     ssl_prefer_server_ciphers on;
<     ssl_ciphers 'DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:TLS_AES_128_GCM_SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-CHACHA20-POLY1305:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256';
<     add_header Strict-Transport-Security "max-age=31536000" always;
79a70
> 
```

**Comment by jasonaowen** [comment]
Thanks! Confirming that I see compressed responses.

Is that file committed anywhere, @bickelj?
