### ISSUE TITLE
Generate type definitions

### ISSUE THREAD

**Issue by jasonaowen** [PhilanthropyDataCommons/service#408]
We are defining the types used in our JSON API multiple times:

- in JSONSchema for ajv to validate
- in OpenAPI to document
- in TypeScript for static analysis
- in the data-viewer repo
- in the data-scripts repo

That's far too much duplication, and we should figure out how to reduce that.

One promising candidate is using OpenAPI SDK generators, as @slifty researched in [a conversation on a data-scripts PR](https://github.com/PhilanthropyDataCommons/data-scripts/pull/24#discussion_r1208115076). Given the OpenAPI schema definition, automated tools should be able to generate some or all of the different outputs we need.

We should probably also publish the artifacts produced by such tools. In particular, since the data-viewer and data-scripts need these type definitions, they'd benefit from being able to install an SDK via npm. Partners might want something similar, too - we should work with them to figure out what SDKs they'd like and publish those, too.

**Comment by slifty** [comment]
We're planning to release a types package and the work is being done over in the sdk repo: https://github.com/PhilanthropyDataCommons/sdk/issues/2

I'm going to close this issue since it is now captured over in issue SDK/2.  Once that's done we'll create the second set of issues related to actually *using* those types.
