### ISSUE TITLE
Create "buckets" on DigitalOcean for file upload

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#564]
As part of #557 I need a few buckets on DigtialOcean's S3 implementation.

In the long run we're going to want a place to store:

1. Unprocessed data
2. Processed populated bulk upload templates (#561)
3. Processed proposal-data-files (#216)

It isn't clear to me if these should be organized as separate buckets or as special key patterns within a single bucket (since I know [S3 doesn't actually have the concept of subdirectories](https://serverfault.com/questions/435827/what-is-the-difference-between-buckets-and-folders-in-amazon-s3).

I get the sense that the more "S3" way is to have one bucket per purpose, and in that sense we'd want to start with two buckets (per environment, that is).  DigitalOcean Spaces allows for up to 100 buckets for $5 / month.

So this would mean something like...

- `unprocessed.local.pdc.org`
- `unprocessed.staging.pdc.org`
- `unprocessed.dev.pdc.org`
- `unprocessed.prod.pdc.org`
- `batch-uploads.local.pdc.org`
- `batch-uploads.staging.pdc.org`
- `batch-uploads.dev.pdc.org`
- `batch-uploads.prod.pdc.org`

(and eventually something like `files.*.pdc.org` for the files related to proposal fields).

Alternatively we could just have ONE universal bucket per environment:

- `local.pdc.org`
- `staging.pdc.org`
- `dev.pdc.org`
- `prod.pdc.org`

^ and within that we would have different keys patterns of `/unprocessed/*` `/batchUploads/*` and `/files/*`.

My understanding is one benefit of the multi-bucket approach is that permissions can be a bit more simple; one benefit of the single-bucket approach is that configuration can be a bit more simple.

**Comment by slifty** [comment]
Note that maybe the `local` buckets are a less ideal approach to having some way of running a local S3 service / mock.  I'll look into tools for something like that (and this would be nice for things like integration tests too).

**Comment by slifty** [comment]
Thanks to @bickelj there are two buckets for local development: 

1. https://pdc-local-unprocessed.nyc3.digitaloceanspaces.com/
2. https://pdc-local-batch-uploads.nyc3.digitaloceanspaces.com/

(I do think it might be worth some day looking into localstack, but this is great for now!)

**Comment by jasonaowen** [comment]
> Alternatively we could just have ONE universal bucket per environment

This is what I would recommend!

Having separate buckets could potentially be more secure in a larger system, but it comes with more complexity in the form of managing multiple credentials. At the moment, there is only one server process, and it would contain full access keys to both buckets; it would be simpler to just have a single bucket and a single key (per environment).

From the documentation, it looks like DigitalOcean Spaces does support [lifecycle rules](https://docs.digitalocean.com/reference/api/spaces-api/#configure-a-buckets-lifecycle-rules), which would allow us to say things like "automatically delete objects starting with the prefix `unprocessed/` after 24 hours". That configuration is [not available through the UI](https://www.howtogeek.com/devops/how-to-set-an-expiration-policy-on-digitalocean-spaces-buckets/), and anyway configuring it is part of setting up the server, so I think we would want to commit the policy JSON in this repo - whether or not we apply it (at startup?) can be a discussion for later.

> local.pdc.org

Let's avoid sharing buckets across multiple unrelated instances - rather, we can have named per-developer buckets for developers that need/want this.

> *.pdc.org

In order for us to have pretty domain names, we'll need to [enable the CDN](https://docs.digitalocean.com/products/spaces/how-to/enable-cdn/) and [configure a subdomain](https://docs.digitalocean.com/products/spaces/how-to/customize-cdn-endpoint/). Unfortunately, as DigitalOcean is not managing our DNS, apparently it will not be able to manage its own certificates; instead, we would have to provide one. It's not clear to me why those two things are linked, and that is an unfortunate limitation.

Rather than take on the burden of certificate management, I propose that for the time being we use the endpoints provided by DigitalOcean, `spacename.region.digitaloceanspaces.com` or `region.digitaloceanspaces.com/spacename`.

**Comment by slifty** [comment]
This all sounds great @jasonaowen -- FWIW I'm "using" the local unprocessed bucket right now but can trivially swap out for whatever the right local bucket is.  I'd value having an allocated DO S3 bucket for my local use in the short term at least (though some day might want to explore localstack and #565).

Point is -- feel free to delete the local buckets that have been created so far / nobody but me is using them.

**Comment by jasonaowen** [comment]
@slifty buckets cannot be renamed, so I've deleted the old (empty) buckets and created two new ones: `pdc-local-slifty` and `pdc-service` for use in production. I believe the same key @bickelj issued you should work to access the new local bucket - please do test it to confirm that!

**Comment by slifty** [comment]
@jasonaowen thanks!

I am sorry to be a pain, but two thoughts regarding those names:

1) regarding `pdc-service` is that intended as production or test (will we have a `pdc-service-test`?).  Would it make sense to specify that in the bucket name, or no?  Relatedly, how will we handle S3 for things like PR deployments (is it possible we *should* be looking into `localstack` and making it part of non-production CI).

2) Regarding the local buckets, it strikes me that they should reference the `service` namespace (e.g. `pdc-service-local-slifty` since this bucket is ONLY intended for use in the service code base.  I don't expect us to have other buckets or non-service applications, but in the event that we did I wouldn't would want potential configuration confusion that might lead to accidental conflict between the service code base's S3 decisions and the unrelated repository's (e.g. that repository might also have a `/unprocessed` key prefix, and it would be odd to me for that to have a potential collision with a completely separate code base / business logic)

**Comment by jasonaowen** [comment]
> regarding `pdc-service` is that intended as production or test

I intended that to be for production.

> will we have a pdc-service-test?

I had intended to, but hadn't created it yet.

>  Relatedly, how will we handle S3 for things like PR deployments

My tentative plan for PR deployments was to have them share a single bucket. It would be possible to have a per-deployment bucket, of course, but I don't yet understand the risk of sharing - can you say more?

> Regarding the local buckets, it strikes me that they should reference the service namespace (e.g. `pdc-service-local-slifty` since this bucket is ONLY intended for use in the service code base.

Sure, happy to use that name!

> ALTERNATIVELY: we could decide that service should not be in any bucket name, and we should adopt a pattern of namespacing via keys (e.g. we'd have `/service/unprocessed` and `/service/bulkUploads`).

Let's not - I don't think unrelated applications should share access to a bucket except under very specific circumstances, so we don't need to pave the way for that use case.

**Comment by slifty** [comment]
w00t -- cool yeah `pdc-service-local-slifty` fixes all my concerns (thank you much for working with me on this!)

**Comment by slifty** [comment]
> It would be possible to have a per-deployment bucket, of course, but I don't yet understand the risk of sharing - can you say more?

Main risk would just be artifacts that last forever -- e.g., I upload 1000 things to test the branch, the branch is merged, the thing lives in that bucket with no path towards being removed / cleaned up.

In theory there would be some risk of the branches stepping on one another's assets for future unknown features, but I think that would be a signal of design mistakes so I'm not as worried about something like that.  For our immediate situation we're using UUIDs so I'm not worried about overlap there.

**Comment by jasonaowen** [comment]
I created `pdc-service-test` and `pdc-service-local-slifty`, and deleted `pdc-local-slifty`. @slifty, can you please verify that the credentials you have grant you write access to `pdc-service-local-slifty`?

**Comment by jasonaowen** [comment]
@slifty confirmed that he was able to use the credentials @bickelj issued him to access the bucket I created!
