### ISSUE TITLE
Consider moving to UUIDs

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#72]
During a conversation with one of our stakeholders the question came up of why use integers for our IDs -- the suggestion was made to use UUIDs instead.

**Comment by slifty** [comment]
@bickelj Just updated the issue with the actual question -- yes that's the question.  What do you think of the idea?

**Comment by bickelj** [comment]
Conceptually, I think UUIDs could be superior to integers. The reasons to prefer integers that I can think of right now are several.
* Compatibility or common support: the JSON data exchange format know integers, database systems know integers, and programming languages (usually) know integers.
* Performance in the database: integers will usually be faster to join, index, scan within an index, etc.
* Friendliness: humans also can read and write integers easily.
* Tradition: it seems to be what we typically do.

The reason we kept 32-bit integers instead of 64-bit integers was the first reason: JavaScript and JSON struggle with 64-bit integer compatibility. What I mean by struggle is the compatibility is not straightforward and requires extra code to support them in a similar manner to 32-bit integers. If JavaScript and JSON struggle with 64-bit integers, how much more will they struggle with UUIDs? If more, then we probably shouldn't use UUIDs unless there are compelling reasons that outweigh the above reasons.

**Comment by bickelj** [comment]
In my first attempts (in https://github.com/PhilanthropyDataCommons/service/pull/103) at processing the spreadsheet provided in https://github.com/PhilanthropyDataCommons/service/issues/95 the UUIDs ended up as the shortCode in PDC. We may not end up doing exactly that, but if so, we would have both a generated integer id as `id` and the supplied UUID as `shortCode`.

**Comment by reefdog** [comment]
Not to bikeshed, but UUIDs in JavaScript/JSON are just strings, right? IMO all the interesting mathy things you can do with integers — like iterating — is precisely why you _don't_ want primary keys as IDs.

I can't speak to the database performance benefits of integers vs. UUIDs, but I'd be a little surprised if this was significant at normal scale considering how regularly UUIDs are used these days.

**Comment by bickelj** [comment]
I would guess that if normal scale means "the whole database including either UUIDs or integer IDs fits into a few GiB of RAM" then we wouldn't notice the performance difference. I still think the other first and third reasons are strong enough to keep integer IDs regardless.

**Comment by reefdog** [comment]
"normal scale" just means "not petabytes of bigdata".

I don't find the first or third reasons very convincing tbh! 😬

Re: compatbility, UUIDs are just as interchangeable as integers, aren't they? This could be my ignorance, but they're just… strings, right?

Re: friendliness, no argument that "user 123" is more legible than "user 89cdd13a-b772-4c04-8d8c-f417004ee5da", but IMO that's an _advantage_, as auto-incrementing integer IDs allow two Bad (Or At Least Unintended) Things: ① incrementing through all entities without having been explicitly handed a list of IDs, and ② leaking approximate table size. I much prefer those to be behaviors we explicitly choose to allow (through providing a list of IDs and a total object count, respectively) rather than being implicitly gleanable.

**Comment by bickelj** [comment]
Suppose, for example, we used blake3 to compute a 64-bit hash of the natural key and used that as a single-column ID for convenience of writing joins, having an integer ID, but not a predictable one, optionally also a hex string as it would be interchangeable.

**Comment by slifty** [comment]
I'd like to suggest we close this issue for now.

I don't see us moving from UUIDs as part of the current data model, and we can incorporate this into the larger #396 conversation.
