### ISSUE TITLE
Fix DB result variable names

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#73]
I made a mistake when naming the variable that contains a DB result (I named it as though it contained the resulting *object(s)* which is actually one level deeper.

I'd like to see this fixed in the two endpoints we have so far in order to prevent further repetition of the error.

**Comment by bickelj** [comment]
In another place I commented that `result` is less narrow and clear than `opportunities`. But I see your point that one could get the impression that the variable has the ultimate, unwrapped object representation of the opportunity when it is named `opportunity`. So I still don't like `result` because everything is a result of something, so it's not a good name. OK, OK, it kind of hints that it "came from a database" because we call data from the database a "result" but naming something after what process produced it rather than the thing itself is not as good as naming it what it is (regardless of how produced). Regardless of all that, the point is well taken that it is a database result set or database rows representation and not the preferred object representation and that these are two different representations of the data, so the distinction is useful. What do you think of `opportunitiesRows`? The `rows` hints that it has some kind of tabular representation or database-ish representation. Or `opportunitiesDbResult`? Or something else?

**Comment by slifty** [comment]
To be clear though it is a `Result` type -- so I think anything that doesn't include `result` is going to be a weird misdirect of a name.  BUT I do hear your point -- what do you think of `queryResult`?

I do think that + the context of the fact that it's a parameter for a handler of a `.query` should make it clear what it is.  Plus we stop using it darn quickly!

Does that feel more comfortable?

**Comment by bickelj** [comment]
Calling it `queryResult` is an improvement over `result` but still pretty generic and repeats the type of the thing in the name. We wouldn't name an integer `integer` nor `fooInteger` nor `intFoo` so perhaps repeating `result` is redundant too. If there is a way to call it what it really is at a higher level with a name related to the purpose, intent, or essence of the underlying entity, I prefer that. As for great options, I don't have any off the top of my head, only these: `opportunitiesFromDb`, `opportunitiesRaw`, `rawOpportunities`, `wrappedOpportunities`, `dbOpportunities`. These all have their ambiguities too but the thing they have in common is an attempt to say what the thing is that we care about at a higher level ("opportunities").

If we were to create a more generic function then I think the more generic name is appropriate.

**Comment by slifty** [comment]
Word -- I'll take a stab at something better and update the PR(s)

(also ty for engaging in this convo I know it's kind of a pedantic change to raise in the first place)

**Comment by slifty** [comment]
I think, ultimately, this variable is NOT an opportunity (it CONTAINS opportunties) and so anything that implies it is equivalent to a list of opportunities is a misleading variable name.

It *IS* a query result (and sure, since we're in typescript we also happen to have a name).

So I think I'll be leaning to something like `opportunityFetchAllResult` <-- I admit I do think this is ironically redundant in a different way since the context of the parameter makes it clear it's the result of the opportunity query (in the same way that we don't name our `res` and `req` parameters to the handler `getOpportunityRes` and `getOpportunityReq`)

That said, it's not generic and it is also not inaccurate.  I'll update the PR to see how it feels!

**Comment by slifty** [comment]
`fetchByIdResult` <-- this feels right!

**Comment by bickelj** [comment]
Bear with me on an analogy. Suppose we know a temperature at which action should be taken. Suppose we use software to create an alert. Suppose we create a constant or variable to represent the actionable threshold. If we used a language with only primitive types, perhaps we could say something like `float feverTemperatureF = 100.4`.  We probably would not say `float floatVariable = 100.4`. We could also represent it like `int feverTemperatureC = 38`. We probably would not say `int intVariable = 38`. In each respective case the value really is a float and really is an int. But these are each a different representation of one underlying thing: an actionable temperature. If we had a type system and library that provided a `Hotness` type, then we might use something like `Hotness feverLevel = Hotness.fromCelsius(38)` and we don't have to repeat the word temperature nor specify the units because the type and library covers it. Instead we named it after what it is or what we intend to do with it or how it is meaningful. We could still name it `Hotness variableOfBitsOnAComputer ...` and that would be true, but not as good as naming it with regard to purpose.

I see your point about the context of the "opportunities" already present in the name of the file, the method, and the file with the particular SQL query. I think this point is well taken. Suppose we assume that every variable in the method contains some representation of opportunities unless marked otherwise, then yeah, it would be redundant to add the word opportunity.

Now that we've gone down the pedantic rabbit hole, though, I wonder why the word "fetch" is used rather than "select", it seems that the query really does a `select from...` so what benefit is there to changing it to `fetch`?

**Comment by slifty** [comment]
**First:** agree re `fetch` vs `select` -- good call!

**Second:**  I'm totally fine with including the word opportunity to the variable name, just so long as we specify that the purpose of the variable is clearly to store a query result.  FWIW I had tried it at first and it started getting a little long (e.g. `fetchOpportunityByIdQueryResult` or `selectOpportunityByIdQueryResult`).

What about `opportunityQueryResult`?

---

Your point about primitives is a good one and I completely agree (I believe that's what Hungarian notation leaned on -- and there's a reason we don't do that any more!)

That said, I don't *think* this `Result` scenario is an example of Hungarian notation, since in this case the term `Result` is very meaningful in terms of defining exactly what this variable exists to hold.

As a flip side analogy: imagine we created a a `Address` type that had robust address attributes.  I don't think we'd suddenly say that `businessAddress` is a poor variable name just because it the type happens to share the same name as the meaning of the represented data.

Whereas `int` has nothing to do with the meaning of the `temperature` in the primitive example, which is why we wouldn't reference `int` in the variable name.

---

Also just want to take a step back and make sure none of what I'm saying is coming off as confrontational / make sure everything's feeling copacetic.  The amount of words spent in this issue is really just in that spirit of enjoying shared exploration of a nerdy topic.  If this convo is raising your blood pressure at all I'll pull the parachute and close the issue right now!

**Comment by bickelj** [comment]
It is all good and well-taken too. A good name distinguishes something from the things around it and since all the variables have opportunities inside, it is not so bad to include the word "result" in there. It is not so bad a change after this discussion, it is back in the neutral or good category. The only reason I had pushed back was my first inclination was that we went not from OK to OK or OK to better but from OK to worse. You have convinced me that it's from OK to OK now.
