### ISSUE TITLE
Demonstrate how a user will filter to their own data

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/service#939]
The API will soon allow filtering data by creator with the `createdBy={userId}` param. However, currently, the front-end has no way of knowing user IDs.

While there are several theoretical interfaces (like a front-end user admin) where these may need to be discoverable, the only current need is for admins — who can see more than just "their stuff" — to filter views to only "their stuff". E.g., letting admins switch between viewing "all proposals" and only "my proposals", or, hard-coding a front-end filter on the Bulk Uploads page so that admins only see their own uploads.

The front-end will need something like an endpoint to retrieve the current user's ID, or, a keyword param (or magic `createdBy` value) that proxies to `createdBy={my user ID}`, or something.

Opening this as a discussion! If there's already a solution or existing task, feel free to close.

**Comment by slifty** [comment]
@reefdog what do you think of a new API endpoint of GET `/me` which would return the user object associated with you?

Some other ideas that I had were:

1. `?createdBy=me` being special -- I don't love this because the type of `createdBy` is currently a number, and although some day I'd like to make references more fancy I don't LOVE shaving that yak right now, and it would increase complexity.
2. `?createdBy=0` being special / referring to you -- I don't love this either since it doesn't feel super intuitive (why would 0 mean me?)
3. a special `/bulkUploads/mine` endpoint or some such thing -- feels awkward.

Anyway, if you think that `/me` would be useful in general I think it could solve the problem / not force API design changes elsewhere, and plus you might want to know that object for other reasons (especially if the object gets more complex some day)

**Comment by reefdog** [comment]
In terms of API design, I agree your preference (I'll call it option 5) is the cleanest. (A nice thing about `/users/me` is that it's basically unhackable, short of the same JWT manipulation any call is vulnerable to. Is `/users?authenticationId={sub}` any less secure for some reason? I'm not sure whether `sub` is the equivalent of a public key, or is decoded data or what.)

I do have concerns about implementation cost to the front end. We'll have to peel back our auth library to figure out how to make a dependent external/API call during the login flow. For the standard flow (click "Log in", redirect to Keycloak, redirect back to standard landing spot) it's no problem.

But for the "try to access a protected resource, redirect to Keycloak, redirect back to protected resource" it's trickier, or at least currently our own yak shave. That redirect behavior comes for free from the library. Will we be able to insert a dependent API call (and response handler) into the process in a way that still redirects to the requested resource at the end (and handles errors from that API call)?

So of course I have a selfish preference for the magic of options 1 or 3, which doesn't require me to do any preflight. (I agree 2 is weird. 1 and 3 require API consumer training too, but their magic is substantially more intuitive.)

That said, I know the API needs to be designed for more than just the front end's narrow concerns. If option 5 is very fast for you to implement, then we can at least give it a go. I just think we — the front-end — should time-box using it, before asking you to SHAVE THAT YAK.

What do you think?

**Comment by slifty** [comment]
I believe this is now done (from a backend PoV) -- there is more to do but I think this issue is done.
