### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#96]
We need:

1) The ability for users of our API to authenticate (with a role).
2) ~~The ability for our API to reject access to specific endpoints depending on the role of the authenticated user.~~

We're thinking [KeyCloak](https://www.keycloak.org/) is the way to go here.

For this iteration I think our goal is ~~*API key based authentication*~~ OAuth 2 authentication.

The intent would be that tell API clients to pass a [`Authorization: Bearer ######`](https://swagger.io/docs/specification/authentication/bearer-authentication/) header token to *all calls* to our system.  That token is then used to authenticate the user and identify their roles.

~~This article could be useful for inspiration (but may not be the exact pattern to use): http://www.zakariaamine.com/2019-06-14/extending-keycloak/~~

**Comment by bickelj** [comment]
Much of the related work can be found in PR #93, PR #97, https://github.com/PhilanthropyDataCommons/keycloak-extensions/pull/1, https://github.com/PhilanthropyDataCommons/deploy/pull/50.

To summarize what I have learned when integrating with keycloak:
* It was straightforward to get keycloak up and running using the guides at https://www.keycloak.org
* If we terminate TLS at the load balancer only (but have keycloak serve plain HTTP within the docker overlay network) then we cannot seem to activate keycloak "production mode" because it wants the backend to also serve via TLS.
* If I use spaces in a realm name in keycloak, I get "Invalid parameter: redirect_uri", so instead of "Philanthropy Data Commons" it is better to use "pdc" as the realm.
* When I included the jar from https://github.com/PhilanthropyDataCommons/keycloak-extensions/pull/1 in the keycloak "providers" directory with keycloak 20.0.0, I got the following warnings: `2022-11-03 22:32:33,608 WARN  [org.keycloak.services] (build-36) KC-SERVICES0047: check (org.philanthropydatacommons.providers.ApiKeyResourceProviderFactory) is implementing the internal SPI realm-restapi-extension. This SPI is internal and may change without notice`, `2022-11-03 22:32:34,722 WARN  [org.keycloak.services] (build-36) KC-SERVICES0047: api-key-registration-generation (org.philanthropydatacommons.providers.RegisterEventListenerProviderFactory) is implementing the internal SPI eventsListener. This SPI is internal and may change without notice`
* It seems like we should not have to extend keycloak to get the functionality we need.
* It also seems like we should not have to use private or internal SPIs to get the functionality we need.
* It seems like keycloak or the protocols it implements avoided unexpiring tokens for a reason.
* If we want to do something simpler, we could omit keycloak, or if we want to do something more complex but using established protocols we could do what keycloak recommends.
* I was able to get a token of "typ": "Bearer" from a test pdc realm's `/token` endpoint when supplying all four of `username`, `password`, `client`, and `client_secret` but not when omitting `client_secret`, despite trying several different `grant_type` values. This led me to read more about OAuth 2.0 and OpenID Connect protocols.
* Keycloak implements, streamlines, and recommends the OpenID Connect protocol.
* The OpenID Connect protocol is a kind of profile and/or authentication mechanism on top of OAuth 2.0 (see https://openid.net/specs/openid-connect-core-1_0.html).
* Many terms used in keycloak come from OpenID Connect and OAuth 2.0.
* OpenID Connect looks more like a strict protocol versus OAuth 2.0 which looks more like a loose framework.
* A nice overview of the OpenID Connect protocol is at https://openid.net/specs/openid-connect-core-1_0.html#Overview but this overview is missing an implicit step 0 of the end user requesting a resource from the Relying Party aka Client.
* OAuth and OpenID Connect have a specific meaning for "Client" that is not what one might think it is on first glance. It looks like OpenID Connect uses "Relying Party" interchangeably with the OAuth term "Client" when looking over https://openid.net/specs/openid-connect-core-1_0.html#Terminology. OAuth 2.0 "Client" means the application, in our case, the PDC service instance, see https://www.rfc-editor.org/rfc/rfc6749#section-1.1 (NOT the end-user who is authenticating).
* Both @gmurtaza00 and I seemed to agree we only need one "Client" for multiple users.
* The Implicit Flow in OAuth 2.0 seems to be discouraged. From https://www.thomasvitale.com/keycloak-authentication-flow-sso-client/, "Implicit Flow for browser-based application, less secure than the previous one, not recommended and deprecated in OAuth 2.1", the OpenID Connect spec mentions the Token Substitution attack with the Implicit Flow but how OpenID Connect mitigates, and the keycloak interface disables it by default.
* Many of the keycloak examples online do not appear related to our use case of securing an API for mostly external machine users. The closest example seems to be in the keycloak quickstarts, i.e. https://github.com/keycloak/keycloak-quickstarts/blob/latest/service-nodejs/app.js
* Our first implementation of API authentication will be simple and without keycloak until we figure out the most fitting way to do it using a keycloak instance. See  https://github.com/PhilanthropyDataCommons/service/pull/113

**Comment by bickelj** [comment]
I think the current/temporary solution slows things down a bit by reading a file every request (I am not certain this is happening but it is a guess). Regardless, we need to get keycloak set up correctly for our use case.

Discussions of interest:
https://groups.google.com/g/keycloak-user/c/75iuKmiYvBU/m/qapTtBASAAA

**Comment by bickelj** [comment]
I will try out the suggestion of unchecking all the boxes on the client and see if users can authenticate without client credentials.

**Comment by bickelj** [comment]
I don't see any difference when unchecking the boxes on the client. I tried to get a token from the token endpoint with just the user credentials and no dice with multiple grant types.

I posted https://groups.google.com/g/keycloak-user/c/ozmeDOh8boI in hopes that someone points me in the right direction.

**Comment by bickelj** [comment]
I see the awkwardness of the "standard" flow in that when I do this:
```
curl -vvv --cacert /home/reverse-proxy/cert.pem -c cookies_20221117  -X GET 'https://localhost/auth/realms/pdc/protocol/openid-connect/auth/?client_id=pdc-service&redirect_uri=https://localhost/&state=abcd&scope=openid&response_mode=fragment&response_type=code&nonce=abcdef'
```
The response from the OpenID Connect Provider (OP) aka Authorization Service (AS) is an html web page along with some cookies. So I would have to do some rudimentary parsing to grab the `action` attribute, make an assumption that `username` and `password` are always there (or parse those inputs as well), and enable saving cookies and re-sending those cookies.

**Comment by slifty** [comment]
I think this is the flow we want:

```
If there is no user context, the remote service can receive a service
account token which it can receive after authenticating with its own
client id and secret. You can restrict which token are valid by
requiring specific scopes or roles. 
```

The client would use their ID and Secret to get a service account token (no user interaction needed).  That token would be the bearer token.

**Comment by bickelj** [comment]
That sounds great on the surface. In that case we would be creating a client for each user instead of a user for each user. And then do we want to create a service account for each client as well? So for N users we would be creating N clients, each with a service account user. Is that really what the person posting means?

**Comment by bickelj** [comment]
I guess that fits in with https://www.keycloak.org/docs/latest/securing_apps/#terminology
> Most often, clients are applications and services...
> Clients can also be entities only interested in obtaining tokens and acting on their own behalf for accessing other services. ...
> A service account is a type of client that is able to obtain tokens on its own behalf.

I am still scratching my head as to why we would not set up Users.

**Comment by bickelj** [comment]
Very helpful overview showing that the expected use case for bearer-only tokens are services/apps/Clients calling services/apps/Clients. https://invidious.weblibre.org/watch?v=FyVHNJNriUQ

But Thomas also has some up-to-date example code:
https://github.com/thomasdarimont/keycloak-project-example/blob/dd851b6bd83bf522c409a44c8067b91545d050b2/apps/backend-api-node-express/src/express.js

**Comment by slifty** [comment]
Yeah -- I believe each client is a client (it so happens our users are client developers, but from an oauth POV they are clients)

**Comment by bickelj** [comment]
I think a concrete example list of users and exact steps would help.

**Comment by bickelj** [comment]
It probably should use `x-forwarded-proto` and `x-forwarded-host`, if available, instead.
```
  "req": {
    "id": 22168,
    "method": "GET",
    "url": "/applicants",
    "query": {},
    "params": {},
    "headers": {
      "x-forwarded-for": "172.25.0.1",
      "x-real-ip": "172.25.0.1",
      "x-forwarded-proto": "https",
      "x-forwarded-host": "the_host",
      "host": "the_host",
```

**Comment by bickelj** [comment]
From https://github.com/keycloak/keycloak-nodejs-connect/issues/348#issuecomment-1320992585 this package is deprecated?

**Comment by bickelj** [comment]
That example was continuing an earlier attempt from https://github.com/keycloak/keycloak-quickstarts/blob/latest/service-nodejs/app.js but perhaps I should start instead with Thomas' example I found at https://github.com/thomasdarimont/keycloak-project-example/blob/dd851b6bd83bf522c409a44c8067b91545d050b2/apps/backend-api-node-express/src/express.js

**Comment by bickelj** [comment]
Thomas' example assumes our software is calling our software again. Round and round we go.

**Comment by bickelj** [comment]
Now my best guess is "implicit flow" is what we want but again I see recommendations against it. Regardless, I will try it to see.

**Comment by bickelj** [comment]
Even with "implicit flow" there is a redirect to a login page. I was able to successfully authenticate but then nginx complained on the first response that "upstream sent too big header while reading response header from upstream" so I need to increase some limits in the reverse proxy.

**Comment by bickelj** [comment]
I was able to get a Bearer access token with implicit flow using curl, but boy is that tedious, and it does involve an html page. Given that two folks have now recommended it on the keycloak users forum, next to investigate is the Device Authorization Grant which might be the best fit.

**Comment by bickelj** [comment]
As for the Device Authorization Grant, it still expects a browser interaction with the user to grant consent for the process that is asking for access, but then provides Bearer access_token and refresh_token. Client Authentication set to Off (this makes it a public client rather than confidential, meaning we expect public users to access it, I think) and Standard Flow still enabled, Implicit Flow still enabled, and OAuth 2.0 Device Authorization Grant enabled. The nice thing is that the browser flow is expected to be separate from the device/software/whatever that is attempting to gain authorization.

I guess we could enable the Standard flow and Device Authorization Grant flow and let the caller choose.

**Comment by bickelj** [comment]
Following the example at https://github.com/thomasdarimont/keycloak-project-example/blob/dd851b6bd83bf522c409a44c8067b91545d050b2/apps/backend-api-node-express/src/express.js (with some changes due to type changes in some of the libraries since that was written) it appears to partially work, meaning I was able to get a failure when attempting to access a protected resource, and a different failure when passing a bearer token.

**Comment by bickelj** [comment]
Naturally testing would be a pain, I'm not sure plain http mocking would be enough without finagling, but perhaps this would? https://www.npmjs.com/package/mock-jwks

**Comment by bickelj** [comment]
It is helpful to enable `DEBUG='jwks,nock.*` while troubleshooting the tests.

**Comment by bickelj** [comment]
It is also helpful to add this to the `errorHandler.ts` function `errorHandler`:
```typescript
  if (err instanceof Error)
  {
    logger.debug(err.stack);
  }
```
This way the stack trace is not lost but also not sent along to the caller.

**Comment by bickelj** [comment]
I have a passing test using `mock-jwks` and a mock token like this:
```typescript
      const aMomentAgo = Math.round(new Date().getTime() / 1000);
      const accessToken = jwksMock.token({
        exp: aMomentAgo + 100000,
        iat: aMomentAgo,
        iss: jwtOptions.issuer,
        aud: 'account',
        typ: 'Bearer',
        azp: 'pdc-service',
        realm_access: {
          roles: [
            'users-role',
            'default-roles-pdc',
          ],
        },
      });
```
The issuer comes from the real `jwtOptions` but the `jwtOptions` uses env var, such that a value in `.env.test` can set it to a fake URL as seen below in the resulting JWT encoded as `eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImIzQkZSbE5zUnpJdlVHZElhRFpuVHpSNlkzTkdWVU5tZFhFNFBRIn0.eyJleHAiOjE2NjkzMjE4NTksImlhdCI6MTY2OTIyMTg1OSwiaXNzIjoiaHR0cHM6Ly9mYWtlLWF1dGgtc2VydmVyL2F1dGgvcmVhbG1zL2Zha2UtcmVhbG0iLCJhdWQiOiJhY2NvdW50IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoicGRjLXNlcnZpY2UiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsidXNlcnMtcm9sZSIsImRlZmF1bHQtcm9sZXMtcGRjIl19fQ.EoV1P6-Cz6toi8t_GmQ3kvWwxVmG1wzNUu64PRlUfaBGZQYxIs4fbvm_Uzuogk5UXsqcPFUlIN-AHupFhPG291z4-0eB13Drc4nt3AVrMBk7fF0n52QBqos6UpwHKew3_vyMYgxV-bWKLhK5q-TKE2VQW7lWhEtsufpsrn3vmc-e5pEAsYR4z_Ehgr7tgH0xY6ljptZK4Yk5iO-keuauAyYtnybxWhAU6-MsOcoKA-YIOIgW9wlFZwU4lig8hf1iPkleFIDeG9HPN-GwooZnLMofslryvCroWAjmRhXIzBEsky7OUdVOdPyqryBjbBYREJzSsSm5sEYK0PpQPCzuqA` and decoded looks like this:
```json
{
  "alg": "RS256",
  "typ": "JWT",
  "kid": "b3BFRlNsRzIvUGdIaDZnTzR6Y3NGVUNmdXE4PQ"
}
```
```json
{
  "exp": 1669321859,
  "iat": 1669221859,
  "iss": "https://fake-auth-server/auth/realms/fake-realm",
  "aud": "account",
  "typ": "Bearer",
  "azp": "pdc-service",
  "realm_access": {
    "roles": [
      "users-role",
      "default-roles-pdc"
    ]
  }
}
```

The weird part is that jwt.io thinks the signature is invalid yet this token was considered valid by the `jwks-rsa` library. Did it not validate the signature or is there a copy/paste error?

**Comment by bickelj** [comment]
The JWT header from the token sent in the request does not match the header we see in https://github.com/levino/mock-jwks/blob/a7fbeae6331f19e18f7b16312b6276936959981c/src/tools.ts#L148 but even if I try to build that header (omitting `"typ": "JWT"` and/or changing order and/or removing spaces) I cannot get jwt.io to say it's a valid signature.

**Comment by bickelj** [comment]
When explicitly calling `verify` from `jsonwebtoken` it returns a token, so it seems to think the JWT is valid. E.g.
```typescript
import fs from 'fs';
import { decode, verify } from 'jsonwebtoken';

const publicKeyFileName = 'x5c.pem';
const publicKey = fs.readFileSync(publicKeyFileName);
const jwt = 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImIzQkZSbE5zUnpJdlVHZElhRFpuVHpSNlkzTkdWVU5tZFhFNFBRIn0.eyJleHAiOjE2NjkzMjE4NTksImlhdCI6MTY2OTIyMTg1OSwiaXNzIjoiaHR0cHM6Ly9mYWtlLWF1dGgtc2VydmVyL2F1dGgvcmVhbG1zL2Zha2UtcmVhbG0iLCJhdWQiOiJhY2NvdW50IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoicGRjLXNlcnZpY2UiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsidXNlcnMtcm9sZSIsImRlZmF1bHQtcm9sZXMtcGRjIl19fQ.EoV1P6-Cz6toi8t_GmQ3kvWwxVmG1wzNUu64PRlUfaBGZQYxIs4fbvm_Uzuogk5UXsqcPFUlIN-AHupFhPG291z4-0eB13Drc4nt3AVrMBk7fF0n52QBqos6UpwHKew3_vyMYgxV-bWKLhK5q-TKE2VQW7lWhEtsufpsrn3vmc-e5pEAsYR4z_Ehgr7tgH0xY6ljptZK4Yk5iO-keuauAyYtnybxWhAU6-MsOcoKA-YIOIgW9wlFZwU4lig8hf1iPkleFIDeG9HPN-GwooZnLMofslryvCroWAjmRhXIzBEsky7OUdVOdPyqryBjbBYREJzSsSm5sEYK0PpQPCzuqA';

const decoded = decode(jwt);
console.log(decoded);
const verified = verify(jwt, publicKey, { complete: true });
console.log(verified);
```
yields
```
{
  exp: 1669321859,
  iat: 1669221859,
  iss: 'https://fake-auth-server/auth/realms/fake-realm',
  aud: 'account',
  typ: 'Bearer',
  azp: 'pdc-service',
  realm_access: { roles: [ 'users-role', 'default-roles-pdc' ] }
}
{
  header: {
    alg: 'RS256',
    typ: 'JWT',
    kid: 'b3BFRlNsRzIvUGdIaDZnTzR6Y3NGVUNmdXE4PQ'
  },
  payload: {
    exp: 1669321859,
    iat: 1669221859,
    iss: 'https://fake-auth-server/auth/realms/fake-realm',
    aud: 'account',
    typ: 'Bearer',
    azp: 'pdc-service',
    realm_access: { roles: [Array] }
  },
  signature: 'EoV1P6-Cz6toi8t_GmQ3kvWwxVmG1wzNUu64PRlUfaBGZQYxIs4fbvm_Uzuogk5UXsqcPFUlIN-AHupFhPG291z4-0eB13Drc4nt3AVrMBk7fF0n52QBqos6UpwHKew3_vyMYgxV-bWKLhK5q-TKE2VQW7lWhEtsufpsrn3vmc-e5pEAsYR4z_Ehgr7tgH0xY6ljptZK4Yk5iO-keuauAyYtnybxWhAU6-MsOcoKA-YIOIgW9wlFZwU4lig8hf1iPkleFIDeG9HPN-GwooZnLMofslryvCroWAjmRhXIzBEsky7OUdVOdPyqryBjbBYREJzSsSm5sEYK0PpQPCzuqA'
}
```
If validation fails, it should throw an error, which it did not.

**Comment by bickelj** [comment]
If I paste the public key into jwt.io it is satisfied. There is probably a better way, but I took the x5c (x.509 cert) from the `jwks` debug logs, created a pem certificate file (adding the ...BEGIN CERT... header and footer), and then ran `openssl x509 -in x5c.pem -text -pubkey` then took the public key output (including the ...BEGIN PUB... header and footer) and pasted it to jwt.io, which then said signature validation passed.

**Comment by bickelj** [comment]
Oh, nice. When disabling caching for tests and then the rate limit is enabled, the tests hit the rate limit when doing more than a couple tests: `JwksRateLimitError: Too many requests to the JWKS endpoint`.

**Comment by bickelj** [comment]
Suppose we try to use a separate URL for each test. The original/prod code does not seem to respect changes to the env and is stuck with the first values it saw.

**Comment by bickelj** [comment]
Here is my best current attempt at a prose summary of the steps a user would take under this proposed Bearer JWT with Device Authorization Grant using keycloak. If there are errors I find later or parts that are unclear, I will strikethrough and replace as needed in edits.

For a caller of the PDC service to make authenticated and authorized calls several steps are needed. In general, we could think of these as initial setup, intermittent maintenance, and then regular calls to the PDC. These are in order from least frequent to most frequent. These steps are present for the two authentication models under consideration and will be compared from several perspectives: the PDC service software perspective, the PDC service user workflow perspective, a security perspective, and a maintenance perspective.

The PDC service software is only concerned with the third step of regular calls. In the model of a pre-shared secret API key, it is straightforward for the PDC service to handle. The PDC service verifies that a given pre-shared secret API key is in the list of currently valid keys before granting access. Likewise the model of a Bearer JSON Web Token is straightforward for the PDC service. The PDC service verifies that a given Bearer JSON Web Token is valid before granting access. The latter model can involve more steps than the former but uses readily-available software libraries to perform them.

From a user workflow perspective, the current pre-shared secret API key model is simple and easy. As a user, I ask the PDC team for a secret key, I save that key to a location accessible to my software, and I direct my software to include that key in an HTTP header. The only intermittent maintenance might be to re-do the initial step of getting a new secret key if the first one got revoked. The proposed Bearer JSON Web Token requires several steps. As a user, my initial setup is to ask the PDC team to create (or myself create) a user in the PDC Authorization Server and then log in to that PDC Authorization Server and set my new secret passphrase. Next, I direct my software to ask the PDC Authorization Server for a secret device code. The response from the PDC Authorization Server includes a secret device code paired with a secret user verification code and a URL. My software prints the URL and code. I visit the PDC Authorization Server URL from any browser, type or paste the secret user verification code, log in with my PDC username and secret passphrase thereby authenticating to the PDC Authorization Server (AS), the PDC AS prompts me to grant access to the device, and I tell the AS to grant access to my software device. In a sense I have allowed the software device to act as my user. After access has been granted (which the AS knows), when my software asks for a Bearer JSON Web Token (JWT) from the AS' token endpoint the AS replies with two tokens: a Bearer JWT and a secret refresh token. I direct my software to include the Bearer JWT in an HTTP header. I further direct my software to get new tokens (both Bearer and refresh) using secret refresh tokens as the Bearer JWTs expire. If time or circumstances break the cycle of refresh tokens or as an alternative to having my software use refresh tokens, I could re-do the device code workflow of granting access.

What could possibly justify such a complex authentication and authorization model?

First, there are key differences in management of and exposure to secrets. In the pre-shared secret API key model, the secrets are known to several parties and are only manually revoked. In the proposed Bearer JWT with Device Authorization Grant model, the secrets have less exposure or are short-lived. The underlying secrets in the pre-shared secret API key model are exposed to these parties that the proposed model would omit: the PDC product team, the messaging service used to communicate the keys to users, and the PDC service software itself. How can this be? For user passphrases, only the users would optionally store them somewhere. The user passphrase never goes to or through the PDC service, only to the Authorization Server (AS). The AS temporarily sees the passphrases but does not store them. The AS instead uses a salt-and-hash scheme for storage. What about the Bearer JWT? The Bearer JWT is indeed visible to the PDC service and is a kind of secret that should not be further exposed, but it has a short validity period of a few minutes. There is another secret on the AS, the PDC AS keypair. The secret AS private key signs the Bearer JWT header and body and the PDC service validates the JWT signature by retrieving and using the public key of its configured AS. What about the user software secrets such as the device code and refresh tokens? Those are entirely between the user's software and the AS. In summary, there is no PDC service secret exposed to the user and there is no user secret exposed to the PDC service.

Second, maintenance. The simple pre-shared secret API key model is currently only an authentication model, not an authorization model. The caller authenticates to the PDC service and the PDC service grants the same access to any one key as any other key. It is a bit too simple on the PDC service side. To enhance it to differentiate between served resources or calling users would be to write our own authorization software into the PDC service. The use of an existing Authorization Service (AS) implementation such as keycloak separates the concern of users, passphrases, groups, roles, and so forth from the PDC service. The PDC service can use the Bearer JWT for authentication by verifying that the expected AS signed it. The PDC service can additionally use the Bearer JWT for authorization by examining its contents, the body of which contains the user's roles. In this regard the PDC service can use roles in the JWT to authorize and ignore usernames entirely. It also has the option to use usernames. Another benefit to the use of an AS is the framework and protocols that the AS implements are standard. This means libraries for the PDC service already exist to validate JWTs using the AS public key with a couple of configuration URIs. The libraries have also considered performance and implement configurable caching, e.g. of the AS public keys, to reduce round trips. Yet another benefit to use of an AS would be when a UI component is used to view data available in the PDC service. The UI can become a Client of the AS such that it can integrate using existing libraries and also share the same users in the same system. The UI can use an alternative flow, e.g. the standard OpenID Connect flow, to authenticate users and get tokens.

The proposed model is certainly more complex at first and not justifiable for a single back-end service. However, when considering additional components such as a UI, key exposure, and authorization capabilities, it is more attractive.

**Comment by bickelj** [comment]
Going back to the original post, it says "all endpoints", though I assume that the swagger documentation endpoint is not included. I'm about to push a change that protects (almost) all endpoints.

**Comment by bickelj** [comment]
There are some steps to get keycloak going:

1. Re-enable the keycloak image in the "deploy" project
2. Get the base configuration included on the test host ("deploy" project: either manually configure or configure via some static file to be deployed automatically)
3. Review/clean up the PR #124 in the "service" project as needed
4. Expand the scope of the solution in PR #124 to all endpoints and remove the old solution

**Comment by jasonaowen** [comment]
After looking at PR #124 and talking with @bickelj, we've decided to split this ticket (and that PR) into two separate but related pieces of work: authentication and authorization. In this first pass, we'll make sure that a known user is accessing the system, meaning that the request comes with a valid token that is issued by the IdP we trust. See #255 for authorization.

**Comment by bickelj** [comment]
Authentication with keycloak is live.
